apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 3  # Updated replica count for scaling
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: pracrdemo.azurecr.io/sample-app:v1
          ports:
            - containerPort: 8045
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-loadbalancer-service
  labels:
    app: portfolio
spec:
  type: LoadBalancer
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 8045